version: 0.2

phases:
  install:
    commands:
      - echo install mvn
  build:
    commands:
      - echo Build started on `date`
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - app/samplekotlinboot-0.0.1-SNAPSHOT.jar