version: 0.2

phases:
  install:
    commands:
  build:
    commands:
      - mvn clean package
artifacts:
  files:
    - target/samplekotlinboot-0.0.1-SNAPSHOT.jar
    - appspec.yml
    - scripts/appstop.sh
    - scripts/appstart.sh